AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda template.

Resources:
  postPackage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./packages/postPackage
      MemorySize: 128
      Timeout: 15
  postInstall:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./packages/install/installPackage
      MemorySize: 256
      Timeout: 15
  postSignup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./signup/postSignup
      MemorySize: 128
      Timeout: 15
  postToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./tokens/postToken
      MemorySize: 128
      Timeout: 15
  getTokens:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./tokens/getTokens
      MemorySize: 128
      Timeout: 15
  deleteToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: ./tokens/deleteToken
      MemorySize: 128
      Timeout: 15
